title: D&D Session Vault
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://walterlivingston.github.io/dnd-session-vault/

heading_anchors: true

color_scheme: dark

collections_dir: collections

collections:
  assets:
    permalink: "/:collection/:path/"
    output: true
  gods:
    permalink: "/:collection/:path/"
    output: true
  items:
    permalink: "/:collection/:path/"
    output: true
  locations:
    permalink: "/:collection/:path/"
    output: true
  party:
    permalink: "/:collection/:path/"
    output: true
  people:
    permalink: "/:collection/:path/"
    output: true
  session_logs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    assets:
      name: Assets
      nav_fold: true
    gods:
      name: Gods
      nav_fold: true
    items:
      name: Items
      nav_fold: true
    locations:
      name: Locations
      nav_fold: true
    party:
      name: Party
      nav_fold: true
    people:
      name: People
      nav_fold: true
    session_logs:
      name: Session Logs
      nav_fold: true

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
