title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

collections:
  assets:
    permalink: "/Assets/"
    output: true
  gods:
    permalink: "/Gods/"
    output: true
  items:
    permalink: "/Items/"
    output: true
  locations:
    permalink: "/Locations/"
    output: true
  party:
    permalink: "/Party/"
    output: true
  people:
    permalink: "/People/"
    output: true
  session_logs:
    permalink: "/Session_Logs/"
    output: true

just_the_docs:
  collections:
    assets:
      name: Assets
      nav_fold: true
    gods:
      name: Gods
      nav_fold: true
    items:
      name: Items
      nav_fold: true
    locations:
      name: Locations
      nav_fold: true
    party:
      name: Party
      nav_fold: true
    people:
      name: People
      nav_fold: true
    session_logs:
      name: Session Logs
      nav_fold: true

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
